name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-mac-x64:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@master

      - name: Install Deps
        run: brew install luajit --HEAD

      - name: Build
        run: |
          git clone https://github.com/MonaSolutions/MonaServer2.git
          make -j${nproc}
        working-directory: MonaServer2

      - name: Upload Artifact 
        uses: actions/upload-artifact@v4
        with: 
          name: MonaServer-macOS-x64
          path: MonaServer2/MonaServer
  

  build-mac-m1:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@master

      - name: Install Deps
        run: brew install luajit --HEAD

      - name: Build
        run: |
          git clone https://github.com/MonaSolutions/MonaServer2.git
          make -j${nproc}
        working-directory: MonaServer2

      - name: Upload Artifact 
        uses: actions/upload-artifact@v4
        with: 
          name: MonaServer-macOS-M1
          path: MonaServer2/MonaServer


  build-win:
      runs-on: windows-latest

      steps:
        - uses: actions/checkout@master
        
        - name: Setup VSC
          uses: TheMrMilchmann/setup-msvc-dev@v3
          with:
            arch: x64

        - name: Build
          run: |
            git clone https://github.com/MonaSolutions/MonaServer2.git
            
            msbuild Mona.sln

        - name: Upload Artifact 
          uses: actions/upload-artifact@v4
          with: 
            name: MonaServer-Win
            path: MonaServer2/MonaServer

        - name: Unit Tests
          run: |
            UnitTests.exe
            cat UnitTests.log/0.log
          working-directory: MonaServer2/UnitTests/Debug/
          

  build-lin:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@master

          - name: Install Deps
            run: |
              git clone https://github.com/LuaJIT/LuaJIT.git
              cd LuaJIT
              make -j${nproc} && sudo make install

          - name: Build
            run: |
              git clone https://github.com/MonaSolutions/MonaServer2.git
              
              make -j${nproc}

          - name: Upload Artifact 
            uses: actions/upload-artifact@v4
            with: 
              name: MonaServer-Linux
              path: MonaServer2/MonaServer
          
          - name: Unit Tests
            run: |
              ./UnitTests
              cat UnitTests.log/0.log
            working-directory: MonaServer2/UnitTests/Debug/